# Generated by Django 3.2.12 on 2024-04-20 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('nome_fazenda', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('area_total_hectares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_agricultavel_hectares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_vegetacao_hectares', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cultura', models.CharField(max_length=100)),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culturas', to='produtores.produtor')),
            ],
        ),
    ]
