# Generated by Django 3.2.12 on 2024-04-21 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cultura',
            old_name='nome_cultura',
            new_name='nome',
        ),
    ]
